spring:
  datasource:
    url: jdbc:mysql://192.168.220.128:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 192.168.220.128
    port: 6379
    password: 01star
  data:
    mongodb:
      uri: mongodb://awei:123456@192.168.220.128:27017/firstDb