spring:
  datasource:
    url: jdbc:mysql://47.120.28.247:3333/test?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: jingziRoot1234
  redis:
    host: 47.113.227.111
    port: 6379
    password: jhkdjhkjdhsIUTYURTU_ECGSam
  data:
    mongodb:
      uri: mongodb://firstDb:YsWaXriryt3hX6Li@8.138.119.99:27017/firstDb